1. 异常指程序运行中出现的不期而至的各种状况。

   如:文件找不到、网络连接失败、非法参数等。

2. 异常发生在程序运行期间，它影响了正常的程序执行流程。

3. 异常体系结构

   <img src="https://img2023.cnblogs.com/blog/3406637/202403/3406637-20240315150909813-280062861.png" alt="image-20240315150915285" style="zoom:40%;" />

4. 异常分类：

   - 检查性异常：最具代表的检查性异常是用户错误或问题引起的异常，这是程序员无法预见的。例如要打开一个不存在文件时，一个异常就发生了，这些异常在编译时不能被简单地忽略。
   - 运行时异常：运行时异常是可能被程序员避免的异常。与检查性异常相反，运行时异常可以在编译时被忽略。
   - 错误ERROR：错误不是异常，而是脱离程序员控制的问题。错误在代码中通常被忽略。例如，当栈溢出时，一个错误就发生了，它们在编译也检查不到的。

## Error和Exception

Error

1. Error类对象由Java虚拟机生成并抛出，大多数错误与代码编写者所执行的操作无关。
2. Java虚拟机运行错误(Virtual MachineError)，当JVM不再有继续执行操作所需的内存资源时，将出现OutOfMemoryError。这些异常发生时，Java虚拟机(JVM)一般会选择线程终止;
3. 还有发生在虚拟机试图执行应用时，如类定义错误(NoClassDefFoundError)、链接错误(LinkageError)。这些错误是不可查的，因为它们在应用程序的控制和处理能力之外，而且绝大多数是程序运行时不允许出现的状况。

Exception

1. 在Exception分支中有一个重要的子类RuntimeException(运行时异常)
   这些异常是不检查异常，程序中可以选择捕获处理，也可以不处理。
2. 这些异常一般是由程序逻辑错误引起的，程序应该从逻辑角度尽可能避免这类异常的发生;

Error和Exception的区别:

1.  Error通常是灾难性的致命的错误，是程序无法控制和处理的，当出现这些异常时，Java虚拟机(JVM)一般会选择终止线程;
2.  Exception通常情况下是可以被程序处理的，并且在程序中应该尽可能的去处理这些异常。

## 捕获和抛出异常

`选中-> Ctrl + Alt + T :自动生成包裹代码块`

try、catch、finally、throw、throws

```java
//finally 可以不要finally。 IO，资源，关闭。
public static void main(String[] args) {
    int a = 1;
    int b = 0;

    try {   //try监控区域
        System.out.println(a / b);
    } catch (ArithmeticException e) { //catch(想要捕获的异常类型)捕获异常
        System.out.println("程序出现异常，变量b不能为0！");
    } finally {  //处理善后工作
        System.out.println("finally");
    }
}
```

要捕获多个异常，需要从小到大的捕获！

```java
try {   //try监控区域
    System.out.println(a / b);
    //new Test().a();
} catch (Error e) { //catch(想要捕获的异常类型)捕获异常
    System.out.println("Error");
} catch (Exception e) {
    System.out.println("Exception！");
} catch (Throwable t) {
    System.out.println("Throwable");
} finally {  //处理善后工作
    System.out.println("finally");
}
```

throw和throws

```java
//假设这个方法中，处理不了这个异常。方法上抛出异常
public void test(int a, int b)throws ArithmeticException{
    if (b == 0) {
        //主动的抛出异常  一般用在方法中
        throw new ArithmeticException();
    }
    //System.out.println(a / b);
}
```

## 自定义异常

1. 用户自定义异常类，只需继承Exception类即可。

2. 在程序中使用自定义异常类，大体可分为以下几个步骤:

   - 创建自定义异常类。

     <img src="https://img2023.cnblogs.com/blog/3406637/202403/3406637-20240315160413841-1531756888.png" alt="image-20240315160419536" style="zoom:33%;" />

   - 在方法中通过throw关键字抛出异常对象。

   - 如果在当前抛出异常的方法中处理异常，可以使用try-catch语句捕获并处理；否则在方法的声明处通过throws关键字指明要抛出给方法调用者的异常，继续进行下一步操作

     <img src="https://img2023.cnblogs.com/blog/3406637/202403/3406637-20240315160338139-1241847922.png" alt="image-20240315160343333" style="zoom:33%;" />

   - 在出现异常方法的调用者中捕获并处理异常。

     <img src="https://img2023.cnblogs.com/blog/3406637/202403/3406637-20240315160945188-914488703.png" alt="image-20240315160951036" style="zoom:33%;" /><img src="https://img2023.cnblogs.com/blog/3406637/202403/3406637-20240315161009166-103809263.png" alt="image-20240315161014982" style="zoom:43%;" />

3. 经验总结

   - 处理运行时异常时，采用逻辑去合理规避同时辅助try-catch处理

   - 在多重catch块后面，可以加一个catch (Exception)来处理可能会被遗漏的异常。 

     Error < Exception < Throwable

   - 对于不确定的代码，也可以加上try-catch，处理潜在的异常

   - 尽量去处理异常，切忌只是简单地调用printStackTrace()去打印输出

   - 具体如何处理异常，要根据不同的业务需求和异常类型去决定

   - 尽量添加finally语句块去释放占用的资源。IO-Scanner